#!/bin/sh

set -eu

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
zshrc_path="$HOME/.zshrc"
start_marker="# >>> dotfiles repository >>>"
end_marker="# <<< dotfiles repository <<<"
git_config="$repo_dir/config/git/config"
legacy_git_config="$repo_dir/git/config"
starship_source="$repo_dir/config/starship/starship.toml"
legacy_starship_source="$repo_dir/starship/starship.toml"
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
starship_target="$config_home/starship.toml"
starship_backup="$config_home/starship.toml.pre-dotfiles"
starship_init='eval "$(starship init zsh)"'
btop_source="$repo_dir/config/btop/btop.conf"
legacy_btop_source="$repo_dir/btop/btop.conf"
btop_config_dir="$config_home/btop"
btop_target="$btop_config_dir/btop.conf"
btop_backup="$btop_config_dir/btop.conf.pre-dotfiles"
tmux_source="$repo_dir/config/tmux/tmux.conf"
legacy_tmux_source="$repo_dir/tmux/tmux.conf"
tmux_target="$HOME/.tmux.conf"
tmux_backup="$HOME/.tmux.conf.pre-dotfiles"
zed_config_dir="$config_home/zed"
zed_settings_source="$repo_dir/config/zed/settings.json"
zed_settings_local="$repo_dir/config/zed/settings.local.json"
zed_settings_target="$zed_config_dir/settings.json"
zed_settings_backup="$zed_config_dir/settings.json.pre-dotfiles"
zed_settings_marker='// Generated by dotfiles install - edit config/zed/settings.json or config/zed/settings.local.json instead.'
zed_agents_source="$repo_dir/config/zed/AGENTS.md"
zed_agents_target="$zed_config_dir/AGENTS.md"
zed_agents_backup="$zed_config_dir/AGENTS.md.pre-dotfiles"
lazygit_source="$repo_dir/config/lazygit/config.yml"
if [ -n "${XDG_CONFIG_HOME:-}" ]; then
    lazygit_config_dir="$XDG_CONFIG_HOME/lazygit"
elif [ "$(uname)" = "Darwin" ]; then
    lazygit_config_dir="$HOME/Library/Application Support/lazygit"
else
    lazygit_config_dir="$HOME/.config/lazygit"
fi
lazygit_target="$lazygit_config_dir/config.yml"
lazygit_backup="$lazygit_config_dir/config.yml.pre-dotfiles"
codex_source="$repo_dir/config/codex/AGENTS.md"
codex_dir="$HOME/.codex"
codex_target="$codex_dir/AGENTS.md"
codex_backup="$codex_dir/AGENTS.md.pre-dotfiles"

install_packages() {
    if ! command -v brew >/dev/null 2>&1; then
        printf 'Homebrew is required. Install it from https://brew.sh, then run this script again.\n' >&2
        exit 1
    fi

    if [ "$(uname)" = "Darwin" ]; then
        printf 'Installing packages from %s/Brewfile\n' "$repo_dir"
        brew bundle --file "$repo_dir/Brewfile"
    else
        linux_brewfile=$(mktemp "${TMPDIR:-/tmp}/dotfiles-brewfile.XXXXXX")
        grep -v '^cask ' "$repo_dir/Brewfile" > "$linux_brewfile"
        printf 'Installing packages from %s/Brewfile (skipping casks; Homebrew Cask only supports macOS)\n' "$repo_dir"
        brew bundle --file "$linux_brewfile"
        rm -f "$linux_brewfile"
    fi
}

install_shell_config() {
    loader_line="[ -r \"$repo_dir/config/zsh/zshrc\" ] && source \"$repo_dir/config/zsh/zshrc\""
    touch "$zshrc_path"
    remove_standalone_starship_init

    if grep -Fxq "$loader_line" "$zshrc_path"; then
        printf 'Shell configuration is already installed.\n'
        return
    fi

    if grep -Fq "$start_marker" "$zshrc_path"; then
        temp_file=$(mktemp "${TMPDIR:-/tmp}/dotfiles-zshrc.XXXXXX")
        awk -v start="$start_marker" -v end="$end_marker" '
            $0 == start { skipping = 1; next }
            $0 == end { skipping = 0; next }
            !skipping { print }
        ' "$zshrc_path" > "$temp_file"
        mv "$temp_file" "$zshrc_path"
        action="Updated"
    else
        action="Added"
    fi

    {
        printf '\n%s\n' "$start_marker"
        printf '%s\n' "$loader_line"
        printf '%s\n' "$end_marker"
    } >> "$zshrc_path"
    printf '%s dotfiles loader in %s\n' "$action" "$zshrc_path"
}

remove_standalone_starship_init() {
    if grep -Fxq "$starship_init" "$zshrc_path"; then
        temp_file=$(mktemp "${TMPDIR:-/tmp}/dotfiles-zshrc.XXXXXX")
        grep -Fvx "$starship_init" "$zshrc_path" > "$temp_file" || true
        mv "$temp_file" "$zshrc_path"
        printf 'Moved Starship startup under dotfiles management.\n'
    fi
}

install_starship() {
    mkdir -p "$config_home"

    if [ -L "$starship_target" ] && [ "$(readlink "$starship_target")" = "$starship_source" ]; then
        printf 'Starship configuration is already installed.\n'
        return
    fi

    if [ -L "$starship_target" ] && [ "$(readlink "$starship_target")" = "$legacy_starship_source" ]; then
        unlink "$starship_target"
        ln -s "$starship_source" "$starship_target"
        printf 'Updated Starship configuration link at %s\n' "$starship_target"
        return
    fi

    if [ -e "$starship_backup" ] || [ -L "$starship_backup" ]; then
        printf 'Cannot install Starship configuration: backup already exists at %s\n' "$starship_backup" >&2
        exit 1
    fi

    if [ -e "$starship_target" ] || [ -L "$starship_target" ]; then
        mv "$starship_target" "$starship_backup"
        printf 'Backed up existing Starship configuration to %s\n' "$starship_backup"
    fi

    ln -s "$starship_source" "$starship_target"
    printf 'Linked Starship configuration at %s\n' "$starship_target"
}

uninstall_starship() {
    if [ -L "$starship_target" ] && { [ "$(readlink "$starship_target")" = "$starship_source" ] || [ "$(readlink "$starship_target")" = "$legacy_starship_source" ]; }; then
        unlink "$starship_target"
        printf 'Removed Starship configuration link at %s\n' "$starship_target"

        if [ -e "$starship_backup" ] || [ -L "$starship_backup" ]; then
            mv "$starship_backup" "$starship_target"
            printf 'Restored previous Starship configuration.\n'
        fi
    else
        printf 'No managed Starship configuration link found.\n'
    fi
}

install_btop() {
    mkdir -p "$btop_config_dir"

    if [ -L "$btop_target" ] && [ "$(readlink "$btop_target")" = "$btop_source" ]; then
        printf 'btop configuration is already installed.\n'
        return
    fi

    if [ -L "$btop_target" ] && [ "$(readlink "$btop_target")" = "$legacy_btop_source" ]; then
        unlink "$btop_target"
        ln -s "$btop_source" "$btop_target"
        printf 'Updated btop configuration link at %s\n' "$btop_target"
        return
    fi

    if [ -e "$btop_backup" ] || [ -L "$btop_backup" ]; then
        printf 'Cannot install btop configuration: backup already exists at %s\n' "$btop_backup" >&2
        exit 1
    fi

    if [ -e "$btop_target" ] || [ -L "$btop_target" ]; then
        mv "$btop_target" "$btop_backup"
        printf 'Backed up existing btop configuration to %s\n' "$btop_backup"
    fi

    ln -s "$btop_source" "$btop_target"
    printf 'Linked btop configuration at %s\n' "$btop_target"

    if ! command -v btop >/dev/null 2>&1; then
        printf 'btop is not installed. Run: brew bundle --file "%s/Brewfile"\n' "$repo_dir"
    fi
}

uninstall_btop() {
    if [ -L "$btop_target" ] && { [ "$(readlink "$btop_target")" = "$btop_source" ] || [ "$(readlink "$btop_target")" = "$legacy_btop_source" ]; }; then
        unlink "$btop_target"
        printf 'Removed btop configuration link at %s\n' "$btop_target"

        if [ -e "$btop_backup" ] || [ -L "$btop_backup" ]; then
            mv "$btop_backup" "$btop_target"
            printf 'Restored previous btop configuration.\n'
        fi
    else
        printf 'No managed btop configuration link found.\n'
    fi
}

install_tmux() {
    if [ -L "$tmux_target" ] && [ "$(readlink "$tmux_target")" = "$tmux_source" ]; then
        printf 'tmux configuration is already installed.\n'
        return
    fi

    if [ -L "$tmux_target" ] && [ "$(readlink "$tmux_target")" = "$legacy_tmux_source" ]; then
        unlink "$tmux_target"
        ln -s "$tmux_source" "$tmux_target"
        printf 'Updated tmux configuration link at %s\n' "$tmux_target"
        return
    fi

    if [ -e "$tmux_backup" ] || [ -L "$tmux_backup" ]; then
        printf 'Cannot install tmux configuration: backup already exists at %s\n' "$tmux_backup" >&2
        exit 1
    fi

    if [ -e "$tmux_target" ] || [ -L "$tmux_target" ]; then
        mv "$tmux_target" "$tmux_backup"
        printf 'Backed up existing tmux configuration to %s\n' "$tmux_backup"
    fi

    ln -s "$tmux_source" "$tmux_target"
    printf 'Linked tmux configuration at %s\n' "$tmux_target"

    if ! command -v tmux >/dev/null 2>&1; then
        printf 'tmux is not installed. Run: brew bundle --file "%s/Brewfile"\n' "$repo_dir"
    fi
}

uninstall_tmux() {
    if [ -L "$tmux_target" ] && { [ "$(readlink "$tmux_target")" = "$tmux_source" ] || [ "$(readlink "$tmux_target")" = "$legacy_tmux_source" ]; }; then
        unlink "$tmux_target"
        printf 'Removed tmux configuration link at %s\n' "$tmux_target"

        if [ -e "$tmux_backup" ] || [ -L "$tmux_backup" ]; then
            mv "$tmux_backup" "$tmux_target"
            printf 'Restored previous tmux configuration.\n'
        fi
    else
        printf 'No managed tmux configuration link found.\n'
    fi
}

install_zed() {
    mkdir -p "$zed_config_dir"

    if [ -f "$zed_settings_target" ] && [ "$(head -n 1 "$zed_settings_target")" = "$zed_settings_marker" ]; then
        :
    elif [ -e "$zed_settings_backup" ] || [ -L "$zed_settings_backup" ]; then
        printf 'Cannot install Zed settings: backup already exists at %s\n' "$zed_settings_backup" >&2
        exit 1
    elif [ -e "$zed_settings_target" ] || [ -L "$zed_settings_target" ]; then
        mv "$zed_settings_target" "$zed_settings_backup"
        printf 'Backed up existing Zed settings to %s\n' "$zed_settings_backup"
    fi

    if ! command -v jq >/dev/null 2>&1; then
        printf 'jq is required to merge Zed settings. Run: brew bundle --file "%s/Brewfile"\n' "$repo_dir" >&2
        exit 1
    fi

    zed_tmp_base=$(mktemp "${TMPDIR:-/tmp}/dotfiles-zed-base.XXXXXX")
    grep -v '^[[:space:]]*//' "$zed_settings_source" > "$zed_tmp_base"

    zed_tmp_overlay=$(mktemp "${TMPDIR:-/tmp}/dotfiles-zed-overlay.XXXXXX")
    if [ -f "$zed_settings_local" ]; then
        grep -v '^[[:space:]]*//' "$zed_settings_local" > "$zed_tmp_overlay"
    else
        printf '{}' > "$zed_tmp_overlay"
    fi

    {
        printf '%s\n' "$zed_settings_marker"
        jq -s '.[0] * .[1]' "$zed_tmp_base" "$zed_tmp_overlay"
    } > "$zed_settings_target"
    rm -f "$zed_tmp_base" "$zed_tmp_overlay"
    printf 'Generated Zed settings at %s\n' "$zed_settings_target"

    if [ -L "$zed_agents_target" ] && [ "$(readlink "$zed_agents_target")" = "$zed_agents_source" ]; then
        printf 'Zed AGENTS.md is already installed.\n'
    else
        if [ -e "$zed_agents_backup" ] || [ -L "$zed_agents_backup" ]; then
            printf 'Cannot install Zed AGENTS.md: backup already exists at %s\n' "$zed_agents_backup" >&2
            exit 1
        fi

        if [ -e "$zed_agents_target" ] || [ -L "$zed_agents_target" ]; then
            mv "$zed_agents_target" "$zed_agents_backup"
            printf 'Backed up existing Zed AGENTS.md to %s\n' "$zed_agents_backup"
        fi

        ln -s "$zed_agents_source" "$zed_agents_target"
        printf 'Linked Zed AGENTS.md at %s\n' "$zed_agents_target"
    fi

    if ! command -v zed >/dev/null 2>&1; then
        if [ "$(uname)" = "Darwin" ]; then
            printf 'Zed is not installed. Run: brew bundle --file "%s/Brewfile"\n' "$repo_dir"
        else
            printf 'Zed is not installed. Install it from https://zed.dev/download\n'
        fi
    fi
}

uninstall_zed() {
    if [ -f "$zed_settings_target" ] && [ "$(head -n 1 "$zed_settings_target")" = "$zed_settings_marker" ]; then
        rm -f "$zed_settings_target"
        printf 'Removed generated Zed settings at %s\n' "$zed_settings_target"

        if [ -e "$zed_settings_backup" ] || [ -L "$zed_settings_backup" ]; then
            mv "$zed_settings_backup" "$zed_settings_target"
            printf 'Restored previous Zed settings.\n'
        fi
    else
        printf 'No managed Zed settings found.\n'
    fi

    if [ -L "$zed_agents_target" ] && [ "$(readlink "$zed_agents_target")" = "$zed_agents_source" ]; then
        unlink "$zed_agents_target"
        printf 'Removed Zed AGENTS.md link at %s\n' "$zed_agents_target"

        if [ -e "$zed_agents_backup" ] || [ -L "$zed_agents_backup" ]; then
            mv "$zed_agents_backup" "$zed_agents_target"
            printf 'Restored previous Zed AGENTS.md.\n'
        fi
    else
        printf 'No managed Zed AGENTS.md link found.\n'
    fi
}

install_lazygit() {
    mkdir -p "$lazygit_config_dir"

    if [ -L "$lazygit_target" ] && [ "$(readlink "$lazygit_target")" = "$lazygit_source" ]; then
        printf 'LazyGit configuration is already installed.\n'
        return
    fi

    if [ -e "$lazygit_backup" ] || [ -L "$lazygit_backup" ]; then
        printf 'Cannot install LazyGit configuration: backup already exists at %s\n' "$lazygit_backup" >&2
        exit 1
    fi

    if [ -e "$lazygit_target" ] || [ -L "$lazygit_target" ]; then
        mv "$lazygit_target" "$lazygit_backup"
        printf 'Backed up existing LazyGit configuration to %s\n' "$lazygit_backup"
    fi

    ln -s "$lazygit_source" "$lazygit_target"
    printf 'Linked LazyGit configuration at %s\n' "$lazygit_target"

    if ! command -v lazygit >/dev/null 2>&1; then
        printf 'LazyGit is not installed. Run: brew bundle --file "%s/Brewfile"\n' "$repo_dir"
    fi
}

uninstall_lazygit() {
    if [ -L "$lazygit_target" ] && [ "$(readlink "$lazygit_target")" = "$lazygit_source" ]; then
        unlink "$lazygit_target"
        printf 'Removed LazyGit configuration link at %s\n' "$lazygit_target"

        if [ -e "$lazygit_backup" ] || [ -L "$lazygit_backup" ]; then
            mv "$lazygit_backup" "$lazygit_target"
            printf 'Restored previous LazyGit configuration.\n'
        fi
    else
        printf 'No managed LazyGit configuration link found.\n'
    fi
}

# Links a single source path to a single target path, backing up anything
# already at the target. Used for Codex's AGENTS.md plus its per-file
# rules/ and per-directory skills/ entries, which are too numerous to give
# each its own hand-written install_<name>/uninstall_<name> pair.
# $1 = source path, $2 = target path, $3 = label for log messages
install_codex_link() {
    if [ -L "$2" ] && [ "$(readlink "$2")" = "$1" ]; then
        printf '%s is already installed.\n' "$3"
        return
    fi

    if [ -e "$2.pre-dotfiles" ] || [ -L "$2.pre-dotfiles" ]; then
        printf 'Cannot install %s: backup already exists at %s\n' "$3" "$2.pre-dotfiles" >&2
        exit 1
    fi

    if [ -e "$2" ] || [ -L "$2" ]; then
        mv "$2" "$2.pre-dotfiles"
        printf 'Backed up existing %s to %s\n' "$3" "$2.pre-dotfiles"
    fi

    ln -s "$1" "$2"
    printf 'Linked %s at %s\n' "$3" "$2"
}

uninstall_codex_link() {
    if [ -L "$2" ] && [ "$(readlink "$2")" = "$1" ]; then
        unlink "$2"
        printf 'Removed %s link at %s\n' "$3" "$2"

        if [ -e "$2.pre-dotfiles" ] || [ -L "$2.pre-dotfiles" ]; then
            mv "$2.pre-dotfiles" "$2"
            printf 'Restored previous %s.\n' "$3"
        fi
    else
        printf 'No managed %s link found.\n' "$3"
    fi
}

install_codex() {
    mkdir -p "$codex_dir" "$codex_dir/rules" "$codex_dir/skills"

    install_codex_link "$codex_source" "$codex_target" "Codex AGENTS.md"

    for rules_file in "$repo_dir"/config/codex/rules/*.rules; do
        [ -e "$rules_file" ] || continue
        rules_name=$(basename "$rules_file")
        install_codex_link "$rules_file" "$codex_dir/rules/$rules_name" "Codex rule ($rules_name)"
    done

    for skill_dir in "$repo_dir"/config/codex/skills/*; do
        [ -d "$skill_dir" ] || continue
        skill_name=$(basename "$skill_dir")
        install_codex_link "$skill_dir" "$codex_dir/skills/$skill_name" "Codex skill ($skill_name)"
    done
}

uninstall_codex() {
    uninstall_codex_link "$codex_source" "$codex_target" "Codex AGENTS.md"

    for rules_file in "$repo_dir"/config/codex/rules/*.rules; do
        [ -e "$rules_file" ] || continue
        rules_name=$(basename "$rules_file")
        uninstall_codex_link "$rules_file" "$codex_dir/rules/$rules_name" "Codex rule ($rules_name)"
    done

    for skill_dir in "$repo_dir"/config/codex/skills/*; do
        [ -d "$skill_dir" ] || continue
        skill_name=$(basename "$skill_dir")
        uninstall_codex_link "$skill_dir" "$codex_dir/skills/$skill_name" "Codex skill ($skill_name)"
    done
}

install_dotfiles() {
    install_packages
    install_shell_config

    if git config --global --get-all include.path 2>/dev/null | grep -Fxq "$legacy_git_config"; then
        git config --global --fixed-value --unset-all include.path "$legacy_git_config"
        printf 'Removed obsolete Git include for %s\n' "$legacy_git_config"
    fi

    if git config --global --get-all include.path 2>/dev/null | grep -Fxq "$git_config"; then
        printf 'Git configuration is already installed.\n'
    else
        git config --global --add include.path "$git_config"
        printf 'Added Git include for %s\n' "$git_config"
    fi

    install_starship
    install_btop
    install_tmux
    install_zed
    install_lazygit
    install_codex
}

uninstall_dotfiles() {
    if [ -f "$zshrc_path" ] && grep -Fq "$start_marker" "$zshrc_path"; then
        temp_file=$(mktemp "${TMPDIR:-/tmp}/dotfiles-zshrc.XXXXXX")
        awk -v start="$start_marker" -v end="$end_marker" '
            $0 == start { skipping = 1; next }
            $0 == end { skipping = 0; next }
            !skipping { print }
        ' "$zshrc_path" > "$temp_file"
        mv "$temp_file" "$zshrc_path"
        printf 'Removed dotfiles loader from %s\n' "$zshrc_path"
    else
        printf 'No dotfiles loader found in %s.\n' "$zshrc_path"
    fi

    git config --global --fixed-value --unset-all include.path "$git_config" 2>/dev/null || true
    git config --global --fixed-value --unset-all include.path "$legacy_git_config" 2>/dev/null || true
    printf 'Removed Git include for %s, if it was present.\n' "$git_config"

    uninstall_starship
    uninstall_btop
    uninstall_tmux
    uninstall_zed
    uninstall_lazygit
    uninstall_codex
}

case "${1:-}" in
    "") install_dotfiles ;;
    --uninstall) uninstall_dotfiles ;;
    *)
        printf 'Usage: %s [--uninstall]\n' "$0" >&2
        exit 2
        ;;
esac
